using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.2.2045.20")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2010, Amphora, Inc.")]
[assembly: AssemblyProductAttribute("Symphony")]
[assembly: AssemblyCompanyAttribute("Amphora, Inc.")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyInformationalVersionAttribute("2.2.2045.20")]
[assembly: AssemblyDescriptionAttribute("12/07/2015 07:07:57")]
[assembly: ThemeInfo(ResourceDictionaryLocation.None,ResourceDictionaryLocation.SourceAssembly)]

